### ISSUE TITLE
Relation "pets" does not exist (Postgres)

### ISSUE THREAD

**Issue by jachinte** [micronaut-projects/micronaut-predator#20]
Hi,
I think I found a bug.

Here you can find a minimal setup to replicate the issue:
https://github.com/jachinte/micronaut-predator-issue
**Note**: you need Docker to run the tests

I'm using liquibase to create a postgres database and populate the initial data. And I'm also using predator jdbc.

Liquibase is working well. Here is part of the log for `gradle test --info`:

```
example.repositories.PetRepositoryTest STANDARD_OUT
    20:05:48.434 [Test worker] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
    20:05:52.391 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - SELECT COUNT(*) FROM public.databasechangeloglock
    20:05:52.413 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - CREATE TABLE public.databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT DATABASECHANGELOGLOCK_PKEY PRIMARY KEY (ID))
    20:05:52.435 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - SELECT COUNT(*) FROM public.databasechangeloglock
    20:05:52.442 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - DELETE FROM public.databasechangeloglock
    20:05:52.444 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - INSERT INTO public.databasechangeloglock (ID, LOCKED) VALUES (1, FALSE)
    20:05:52.452 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
    20:05:52.466 [Test worker] INFO  l.lockservice.StandardLockService - Successfully acquired change log lock
    20:05:53.989 [Test worker] INFO  l.c.StandardChangeLogHistoryService - Creating database history table with name: public.databasechangelogtests completed
    20:05:53.992 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - CREATE TABLE public.databasechangelog (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED TIMESTAMP WITHOUT TIME ZONE NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35), DESCRIPTION VARCHAR(255), COMMENTS VARCHAR(255), TAG VARCHAR(255), LIQUIBASE VARCHAR(20), CONTEXTS VARCHAR(255), LABELS VARCHAR(255), DEPLOYMENT_ID VARCHAR(10))
    20:05:54.008 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - SELECT COUNT(*) FROM public.databasechangelog
    20:05:54.011 [Test worker] INFO  l.c.StandardChangeLogHistoryService - Reading from public.databasechangelog
    20:05:54.012 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
    20:05:54.017 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - SELECT COUNT(*) FROM public.databasechangeloglock
    20:05:54.077 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - CREATE SCHEMA myschema
    20:05:54.081 [Test worker] INFO  liquibase.changelog.ChangeSet - Custom SQL executed
    20:05:54.085 [Test worker] INFO  liquibase.changelog.ChangeSet - ChangeSet classpath:db/changelog/01-create-schema.xml::01::miguel ran successfully in 9ms
    20:05:54.088 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - SELECT MAX(ORDEREXECUTED) FROM public.databasechangelog
    20:05:54.096 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('01', 'miguel', 'classpath:db/changelog/01-create-schema.xml', NOW(), 1, '8:d75ddf2fc8a50d9d50a7eb903110a02c', 'sql', '', 'EXECUTED', NULL, NULL, '3.6.3', '3678354023')
    20:05:54.105 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - CREATE TABLE myschema.owners (id BIGSERIAL NOT NULL, name VARCHAR(25), age INTEGER, CONSTRAINT OWNERS_PKEY PRIMARY KEY (id), UNIQUE (id))
    20:05:54.115 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - COMMENT ON TABLE myschema.owners IS 'A table for owners'
    20:05:54.118 [Test worker] INFO  liquibase.changelog.ChangeSet - Table owners created
    20:05:54.120 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - CREATE TABLE myschema.pets (id UUID NOT NULL, name VARCHAR(25), owner_id BIGINT NOT NULL, type VARCHAR(3), CONSTRAINT PETS_PKEY PRIMARY KEY (id), CONSTRAINT fk_owner_id FOREIGN KEY (owner_id) REFERENCES myschema.owners(id), UNIQUE (id))
    20:05:54.130 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - COMMENT ON TABLE myschema.pets IS 'A table for pets'
    20:05:54.132 [Test worker] INFO  liquibase.changelog.ChangeSet - Table pets created
    20:05:54.138 [Test worker] INFO  liquibase.changelog.ChangeSet - ChangeSet classpath:db/changelog/01-create-schema.xml::02::miguel ran successfully in 34ms
    20:05:54.140 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('02', 'miguel', 'classpath:db/changelog/01-create-schema.xml', NOW(), 2, '8:8609a61f2b219fd8e5fb0bb2c4168e4a', 'createTable tableName=owners; createTable tableName=pets', '', 'EXECUTED', NULL, NULL, '3.6.3', '3678354023')
    20:05:54.148 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - INSERT INTO myschema.owners (id, name, age) VALUES ('1', 'Fred', '45')
    20:05:54.151 [Test worker] INFO  liquibase.changelog.ChangeSet - New row inserted into owners
    20:05:54.152 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - INSERT INTO myschema.owners (id, name, age) VALUES ('2', 'Barney', '40')
    20:05:54.157 [Test worker] INFO  liquibase.changelog.ChangeSet - New row inserted into owners
    20:05:54.161 [Test worker] INFO  liquibase.changelog.ChangeSet - ChangeSet classpath:db/changelog/02-insert-initial-data.xml::01::miguel ran successfully in 14ms
    20:05:54.163 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('01', 'miguel', 'classpath:db/changelog/02-insert-initial-data.xml', NOW(), 3, '8:f2d5496329d97e4ca52877cedfdd3248', 'insert tableName=owners; insert tableName=owners', '', 'EXECUTED', NULL, NULL, '3.6.3', '3678354023')
    20:05:54.170 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - INSERT INTO myschema.pets (id, name, type, owner_id) VALUES ('54529912-5932-4337-94e9-b395187ba597', 'Dino', 'DOG', '1')
    20:05:54.178 [Test worker] INFO  liquibase.changelog.ChangeSet - New row inserted into pets
    20:05:54.181 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - INSERT INTO myschema.pets (id, name, type, owner_id) VALUES ('23bc3100-9976-418f-87f8-6cf5a693abfc', 'Baby Puss', 'CAT', '1')
    20:05:54.184 [Test worker] INFO  liquibase.changelog.ChangeSet - New row inserted into pets
    20:05:54.185 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - INSERT INTO myschema.pets (id, name, type, owner_id) VALUES ('d1e6008e-b0fe-4380-8be5-0a99162e75d4', 'Hoppy', 'DOG', '2')
    20:05:54.188 [Test worker] INFO  liquibase.changelog.ChangeSet - New row inserted into pets
    20:05:54.194 [Test worker] INFO  liquibase.changelog.ChangeSet - ChangeSet classpath:db/changelog/02-insert-initial-data.xml::02::miguel ran successfully in 24mspositories.PetRepositoryTest
    20:05:54.196 [Test worker] INFO  liquibase.executor.jvm.JdbcExecutor - INSERT INTO public.databasechangelog (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('02', 'miguel', 'classpath:db/changelog/02-insert-initial-data.xml', NOW(), 4, '8:a38b25b74e768484a17fae0f0fecd93d', 'insert tableName=pets; insert tableName=pets; insert tableName=pets', '', 'EXECUTED', NULL, NULL, '3.6.3', '3678354023')
    20:05:54.207 [Test worker] INFO  l.lockservice.StandardLockService - Successfully released change log lock
```

However, the repositories are not working. There are SQL exceptions indicating that relations "owners" and "pets" do not exist. I believe this is because the SQL queries do not include the schema name.

Here is one of the exceptions:

```
example.repositories.PetRepositoryTest > testRetrievePetAndOwner() STANDARD_OUT
    20:05:55.429 [Test worker] DEBUG io.micronaut.data.query - Executing Query: SELECT pets_.id,pets_.owner_id,pets_.name,pets_.type,pets_owner_.id AS _owner_id,pets_owner_.age AS _owner_age,pets_owner_.name AS _owner_name FROM pets AS pets_ INNER JOIN owners pets_owner_ ON pets_.owner_id=pets_owner_.id WHERE (pets_.name = ?)

example.repositories.PetRepositoryTest > testRetrievePetAndOwner() FAILED
    io.micronaut.data.exceptions.DataAccessException: Error executing SQL Query: ERROR: relation "pets" does not exist
      Position: 149
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$2(DefaultJdbcRepositoryOperations.java:179)
        at io.micronaut.data.jdbc.runtime.spring.SpringJdbcTransactionOperations.lambda$executeRead$1(SpringJdbcTransactionOperations.java:63)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at io.micronaut.data.jdbc.runtime.spring.SpringJdbcTransactionOperations.executeRead(SpringJdbcTransactionOperations.java:60)
        at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.findOne(DefaultJdbcRepositoryOperations.java:139)
        at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:46)
        at io.micronaut.data.runtime.intercept.DefaultFindOptionalInterceptor.intercept(DefaultFindOptionalInterceptor.java:33)
        at io.micronaut.data.intercept.PredatorIntroductionAdvice.intercept(PredatorIntroductionAdvice.java:75)
        at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
        at example.repositories.PetRepository$Intercepted.findByName(Unknown Source)
        at example.repositories.PetRepositoryTest.testRetrievePetAndOwner(PetRepositoryTest.java:36)

        Caused by:
        org.postgresql.util.PSQLException: ERROR: relation "pets" does not exist
          Position: 149
            at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
            at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
            at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
            at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
            at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
            at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
            at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
            at com.sun.proxy.$Proxy52.executeQuery(Unknown Source)
            at io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations.lambda$findOne$2(DefaultJdbcRepositoryOperations.java:143)
            ... 11 more
```

I'm using annotation "Table" to indicate the table name, schema and catalog:

```java
import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(
    name = "pets",
    schema = "myschema",
    catalog = "mycatalog"
)
public class Pet {
    ...
}
```

**Comment by graemerocher** [comment]
yeah the `schema` attribute is not supported, will fill in support for that soon. Thanks for the feedback

**Comment by jachinte** [comment]
@graemerocher I'm getting this error again starting Micronaut Data 1.0.0.M5.
