### ISSUE TITLE
Page cannot be deserialized back to a POJO

### ISSUE THREAD

**Issue by franz-see** [micronaut-projects/micronaut-predator#24]
Trying to deserialize a JSON object back into a Page object (useful in testing) fails with something like

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.micronaut.data.model.Page` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"content":[{"id":1,"name":"DevOps"},{"id":2,"name":"Micro-services"}],"pageable":{"number":0,"sort":{"sorted":false},"size":100,"offset":0,"sorted":false},"totalSize":2,"totalPages":1,"empty":false,"size":100,"offset":0,"pageNumber":0,"numberOfElements":2,"sort":{"number":0,"sort":{"sorted":false},"size":100,"offset":0,"sorted":false}}"; line: 1, column: 1]

	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:265)
```

**Comment by franz-see** [comment]
My worked around for this was to create a mixin on DefaultPage, Pageable, Sort, and Sort.Order

For full code, see https://github.com/franz-see/micronaut-predator-jdbc-example/tree/master/src/main/java/ph/net/see/config

```
@Context
public class JacksonConfig {

    @Inject
    public void configureObjectMapper(ObjectMapper objectMapper) throws ClassNotFoundException {
        Class<?> defaultPageClass = Class.forName("io.micronaut.data.model.DefaultPage");

        SimpleAbstractTypeResolver resolver = new SimpleAbstractTypeResolver();
        resolver.addMapping(Page.class, (Class) defaultPageClass);

        SimpleModule module = new SimpleModule("CustomModel", Version.unknownVersion());
        module.setAbstractTypes(resolver);

        objectMapper.registerModule(module);

        // Note: We cannot use Page.of(..) as @JsonCreator because of
        // https://github.com/FasterXML/jackson-databind/issues/2384
        objectMapper.addMixIn(defaultPageClass, DefaultPageMixin.class);
        objectMapper.addMixIn(Pageable.class, PageableMixin.class);
        objectMapper.addMixIn(Sort.class, SortMixin.class);
        objectMapper.addMixIn(Sort.Order.class, OrderMixin.class);
    }
}
```

```
@JsonIgnoreProperties(ignoreUnknown = true)
public abstract class DefaultPageMixin<T> {

    @JsonCreator
    DefaultPageMixin(
            @JsonProperty("content") List<T> content,
            @JsonProperty("pageable") Pageable pageable,
            @JsonProperty("totalSize") long totalSize) {
    }
}
```

```
@JsonIgnoreProperties(ignoreUnknown = true)
public class OrderMixin {

    @SuppressWarnings("unused")
    @JsonCreator
    public OrderMixin(
            @JsonProperty("property") String property,
            @JsonProperty("direction") Sort.Order.Direction direction,
            @JsonProperty("ignoreCase") boolean ignoreCase) {
    }

}
```

```
@JsonIgnoreProperties(ignoreUnknown = true)
public abstract class PageableMixin {

    @SuppressWarnings("unused")
    @JsonCreator
    static Pageable from(
            @JsonProperty("index") int number,
            @JsonProperty("size") int size,
            @JsonProperty("sort") @Nullable Sort sort) {
        return null;
    }

    @JsonIgnore
    public List<Sort.Order> getOrderBy() {
        return null;
    }
}
```

```
@JsonIgnoreProperties(ignoreUnknown = true)
public class SortMixin {

    @SuppressWarnings("unused")
    @JsonCreator
    static Sort of(@JsonProperty("orderBy") List<Sort.Order> ignore) {
        return null;
    }
}
```

**Comment by graemerocher** [comment]
Thanks for the PR
