### ISSUE TITLE
Groovy: No backing RepositoryOperations configured for repository

### ISSUE THREAD

**Issue by ssadedin** [micronaut-projects/micronaut-predator#25]
I am trying to follow the instructions as best I can but cannot get an example using Groovy to work. Here is what I do:

**Create an application using Micronaut 1.2.0-RC2**

```
mn create-app --lang groovy groovypredator
cd groovypredator
```

**Edit build.gradle to add Predator support**

Add these lines to dependencies:
```
    compileOnly 'io.micronaut.data:micronaut-predator-processor:1.0.0.BUILD-SNAPSHOT'
    compileOnly "io.micronaut.data:micronaut-predator-jdbc:1.0.0.BUILD-SNAPSHOT"     
    implementation 'io.micronaut.data:micronaut-predator-model:1.0.0.BUILD-SNAPSHOT' 
    implementation "jakarta.persistence:jakarta.persistence-api:2.2.2"  
```
(note that some of these weren't in the instructions, but I added them to get the compile to work).

Add this to repositories:

```
  maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }        
```

Add to application.yml:

```yaml
datasources:
    default:
        url: jdbc:h2:file:./testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: ""                                                        
        driverClassName: org.h2.Driver
```

**Create Basic Controller and Domain Class**

Then create a domain class and controller (for convenience, all in 1 file):

```
cat > src/main/groovy/groovypredator/TestController.groovy
package groovypredator

import javax.persistence.Entity         
import javax.persistence.GeneratedValue 
import javax.persistence.Id             
import javax.inject.Inject
import javax.sql.DataSource

import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.data.annotation.Repository
import io.micronaut.data.repository.CrudRepository
import io.micronaut.data.jdbc.annotation.JdbcRepository 
import io.micronaut.data.model.query.builder.sql.Dialect

@Entity                                 
class Thing {                      
    @Id                                 
    @GeneratedValue                     
    Long id                             
                                        
    Thing(Long id) {               
        this.id = id                    
    }                                   
                                        
    Thing() {                      
    }                                   
}                                       

@JdbcRepository(dialect=Dialect.H2)  
interface ThingRepository extends CrudRepository<Thing,Long> {
}

@Controller("/")
class TestController {

    @Inject ThingRepository things

    @Get("/test") 
    def getthing() {

        Thing thing = things.findById(884042)

        "\nFound a thing: hello\n"
    }
}
```
**Error**

I can compile and run the application, but I get this if I hit the URL:

```
curl http://localhost:8080/test/ ; echo
{"message":"Internal Server Error: No backing RepositoryOperations configured for repository. Check your configuration and try again"}
```
With stack trace:
```
12:05:41.637 [pool-1-thread-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: No backing RepositoryOperations configured for repository. Check your configuration and try again
io.micronaut.context.exceptions.ConfigurationException: No backing RepositoryOperations configured for repository. Check your configuration and try again
	at io.micronaut.data.intercept.PredatorIntroductionAdvice.findInterceptor(PredatorIntroductionAdvice.java:102)
	at io.micronaut.data.intercept.PredatorIntroductionAdvice.intercept(PredatorIntroductionAdvice.java:74)
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
	at schism.domain.BreakpointRepository$Intercepted.findById(Unknown Source)
	at io.micronaut.data.repository.CrudRepository$findById.call(Unknown Source)
...
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.data.operations.RepositoryOperations] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1842)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:582)
	at io.micronaut.data.intercept.PredatorIntroductionAdvice.findInterceptor(PredatorIntroductionAdvice.java:99)
```

I'm not sure if I'm missing something obvious or if there is actually something missing from the support or the documentation?

**Comment by ssadedin** [comment]
After some more playing around, this seems to have been solved by changing the scope of the predator-jdbc dependency:

```
    compileOnly "io.micronaut.data:micronaut-predator-jdbc:1.0.0.BUILD-SNAPSHOT"
```

to 

```
    compile "io.micronaut.data:micronaut-predator-jdbc:1.0.0.BUILD-SNAPSHOT"
```

Now I have lots of other issues mapping my fields / classes, but they are different.
