### ISSUE TITLE
Unable to set PreparedStatement: Invalid column type

### ISSUE THREAD

**Issue by recursivecodes** [micronaut-projects/micronaut-predator#39]
I'm getting:

```
Caused by: io.micronaut.data.exceptions.DataAccessException: Unable to set PreparedStatement value: Invalid column type
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.newDataAccessException(JdbcQueryStatement.java:253)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setValue(JdbcQueryStatement.java:108)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setValue(JdbcQueryStatement.java:18)
	at io.micronaut.data.runtime.mapper.QueryStatement.setDynamic(QueryStatement.java:168)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:76)
	at io.micronaut.data.jdbc.mapper.JdbcQueryStatement.setDynamic(JdbcQueryStatement.java:18)
```

When trying a simple many-to-one with the following models:

https://gist.github.com/b4b2f8b37ce8b9f2a16781af13b2db87
https://gist.github.com/131df4d3f30be0d110f7960ae8c9ff87

```
Meal meal = new Meal(100);
mealRepository.save(meal);

Food food = new Food("test", 100, 100, meal);
foodRepository.save(food);
```

Seems what is happening is that when Predator tries to bind the `meal_id` on Food it sees it as an "ENTITY" type and the `statement.setObject()` seems to be failing. Have I modeled this incorrectly?

Edit: I added `@MappedProperty` hoping that it would understand that the Meal id should be treated as a string, but no luck...

**Comment by graemerocher** [comment]
I was not able to reproduce the referenced classes. The commit https://github.com/micronaut-projects/micronaut-predator/commit/0c5083b4e68da579c695c8cb647dffb0f2b83354 adds the classes and a test that verifies this works as expected.

However, from the description it seems that ENTITY type is being passed to `setDynamic`. I am not sure how this is happening and cannot reproduce. However I have pushed an attempted fix https://github.com/micronaut-projects/micronaut-predator/commit/8d7a27e5e91cb89833688fdbd38a5ed895ba6350

If you can verify this fix works for you that would be great.

**Comment by recursivecodes** [comment]
Everything is working properly now. Gracias and thank you.
